name: Deploy_backend

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

env:
  AZURE_FUNCTIONAPP_NAME: "KwCounter" # Set this to your Azure Function App name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "backend" # Set this to the path to your function app project, defaults to the repository root
  AZURE_FUNCTIONAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2

      - name: "Set up Python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4 # Adjust to your Python version

      - name: "Install Azure Functions Core Tools"
        run: |
          npm install -g azure-functions-core-tools@3 --unsafe-perm true
        env:
          AZURE_FUNCTIONS_CORETOOLS_PATH: "/usr/local/lib/node_modules/azure-functions-core-tools"

      - name: "Build and Deploy Azure Function"
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/api
          func azure functionapp publish ${{ env.AZURE_FUNCTIONAPP_NAME }} --publish-local-settings
        env:
          AzureWebJobsStorage: ${{ secrets.AzureWebJobsStorage }}
          FUNCTION_APP_ROOT: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/api
